# Generated by Django 4.1.1 on 2022-11-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='secondary_text',
            field=models.CharField(default='extra field not filled in', max_length=900),
            preserve_default=False,
        ),
    ]
